### ISSUE TITLE
Problem with pedestrian mode

### ISSUE THREAD

**Issue by sylvainar** [mapzen/lrm-mapzen#55] opened 2016-05-26 21:09 UTC
Hey guys !

Nice work first ;)

So i'm having an issue with LRM and Mapzen, my website is able to calculate the routing in auto, bicycle mode, but not in the only mode I really need, pedestrian.

This is the code I'm using : 
`var routing = L.Routing.control({
		router: L.Routing.mapzen('valhalla-TC63npX', {costing:'pedestrian'}),
		formatter: new L.Routing.mapzenFormatter(),
		waypoints: routing_poi_list,
		routeWhileDragging: false,
		collapsible: true,
		draggableWaypoints: false,
		addWaypoints: false
	}).addTo(map);`

And the error (sorry it's in french) :  
`Error : No path could be found for input lrm-mapzen.min.js:1:3757
erreur de syntaxe`

No path could be found : I don't understand why because it works in other modes.
Syntax error ? Why ?

Thanks for your help !

**Comment by hanbyul-here** [comment] 2016-05-27 16:05
Hi!

You can't get pedestrian routing result at all? or is this happening only with some waypoints?

**Comment by sylvainar** [comment] 2016-05-27 16:32
Hey,

Nop, only with some waypoints, but it doesn't work, like, 8 on 10 tries. Here are some screenshots.

**Comment by kevinkreiser** [comment] 2016-05-27 17:05
@sylvainar the problem isnt `lrm` but rather with the valhalla service code. particularly, the problem is that there are really short ways near by that are marked as stairs. pedestrians are allowed on stairs and so the algorithm finds those as the starting point. the  problem is the stairs arent connected to anything. so once the algorithm is on the stairs it cant get off.

we are tracking this issue here: https://github.com/valhalla/loki/issues/127

**Comment by sylvainar** [comment] 2016-05-27 17:23
Great, I suscribe to it. Thanks !

**Closed** 2016-06-01 19:42 UTC
